//
//  AmplitudeEventType.swift
//  PINGLE-iOS
//
//  Created by 정채은 on 3/5/24.
//

import Foundation

public enum AmplitudeEventType: String {
    case openApp = "open_app"
    case closeApp = "close_app"
    case logoutApp = "logout_app"
    case withdrawApp = "withdraw_app"
    case startSignup = "start_signup"
    case completeSignup = "complete_signup"
    case clickMethodOption = "click_method_option"
    case clickExistingGroupCreategroup = "click_existinggroup_creategroup"
    case completeSearchGroup = "complete_search_group"
    case clickExistingGroupEnter = "click_existinggroup_enter"
    case completeExistingGroup = "complete_existinggroup"
    case clickExistingGroupStart = "click_existinggroup_start"
    case completeDoubleCheck = "complete_doublecheck"
    case clickStep1Next = "click_step1_next"
    case clickStep1Info = "click_step1_info"
    case clickStep2Info = "click_step2_info"
    case clickStep3Info = "click_step3_info"
    case clickCreateGroupMake = "click_creategroup_make"
    case completeCreateGroup = "complete_creategroup"
    case clickCreateGroupInvite = "click_creategroup_invite"
    case clickCreateGroupStart = "click_creategroup_start"
    case clickCreateGroupInviteCopy = "click_creategroup_invite_copy"
    case clickCreateGroupInviteShare = "click_creategroup_invite_share"
    case startMyGroup = "start_mygroup"
    case clickInviteCode = "click_invitecode"
    case clickInviteCodeCopy = "click_invitecode_copy"
    case clickInviteCodeShare = "click_invitecode_share"
    case clickOtherGroup = "click_othergroup"
    case clickOtherGroupChange = "click_othergroup_change"
    case clickNewGroup = "click_newgroup"
    case startMeetingHold = "start_meetinghold"
    case clickMeetingCancel = "click_meetingcancel"
    case clickStep1CancelOut = "click_step1_cancel_out"
    case clickStep1CancelStay = "click_step1_cancel_stay"
    case clickStep2CancelOut = "click_step2_cancel_out"
    case clickStep2CancelStay = "click_step2_cancel_stay"
    case clickStep3CancelOut = "click_step3_cancel_out"
    case clickStep3CancelStay = "click_step3_cancel_stay"
    case clickStep4CancelOut = "click_step4_cancel_out"
    case clickStep4CancelStay = "click_step4_cancel_stay"
    case clickStep5CancelOut = "click_step5_cancel_out"
    case clickStep5CancelStay = "click_step5_cancel_stay"
    case clickStep6CancelOut = "click_step6_cancel_out"
    case clickStep6CancelStay = "click_step6_cancel_stay"
    case clickMeetingHold = "click_meetinghold"
    case completeMeetingHold = "complete_meetinghold"
    case scrollRanking = "scroll_ranking"
    case clickSearchMap = "click_search_map"
    case completeSearchMap = "complete_search_map"
    case clickCategoryMap = "click_category_map"
    case clickCurrentlocation = "click_currentlocation"
    case clickListMap = "click_list_map"
    case clickPinMap = "click_pin_map"
    case clickPinParticipants = "click_pin_participants"
    case clickPinChat = "click_pin_chat"
    case clickPinParticipate = "click_pin_participate"
    case clickPinCancel = "click_pin_cancel"
    case clickPinDelete = "click_pin_delete"
    case clickSearchList = "click_search_list"
    case completeSearchList = "complete_search_list"
    case clickCategoryList = "click_category_list"
    case clickMapList = "click_map_list"
    case clickDatesoonarray = "click_datesoonarray"
    case clickRecentcreationarray = "click_recentcreationarray"
    case clickCardParticipants = "click_card_participants"
    case clickCardChat = "click_card_chat"
    case clickCardParticipate = "click_card_participate"
    case clickCardCancel = "click_card_cancel"
    case clickCardDelete = "click_card_delete"
    case clickSoonpingle = "click_soonpingle"
    case scrollSoonpingle = "scroll_soonpingle"
    case clickSoonpingleParticipants = "click_soonpingle_participants"
    case clickSoonpingleMoreChat = "click_soonpingle_more_chat"
    case clickSoonpingleMoreCancel = "click_soonpingle_more_cancel"
    case clickSoonpingleMoreCancelBack = "click_soonpingle_more_cancel_back"
    case clickSoonpingleMoreDelete = "click_soonpingle_more_delete"
    case clickDonepingle = "click_donepingle"
    case scrollDonepingle = "scroll_donepingle"
    case clickDonepingleParticipants = "click_donepingle_participants"
    
}
